-- ============================================================================
-- EcomSkool Companion App — Phase 2: gating engine + storage + prompts
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Storage bucket for brand file uploads (private, 50 MB max)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('brand-files', 'brand-files', false, 52428800)
on conflict (id) do nothing;

-- Storage RLS: bucket is private; all reads/writes go through signed URLs
-- generated by the service-role client on the server — no direct client access.
-- We add a permissive insert policy so the service role (bypasses RLS) can
-- write, and a select policy so signed-URL generation works.
drop policy if exists "brand_files_insert" on storage.objects;
create policy "brand_files_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'brand-files');

drop policy if exists "brand_files_select" on storage.objects;
create policy "brand_files_select" on storage.objects
  for select to authenticated
  using (bucket_id = 'brand-files');

-- ---------------------------------------------------------------------------
-- Add English description to pipeline_steps
-- ---------------------------------------------------------------------------
alter table public.pipeline_steps
  add column if not exists description_en text;

-- ---------------------------------------------------------------------------
-- Seed English descriptions + sample prompt templates
-- (idempotent — on conflict keeps existing admin edits)
-- ---------------------------------------------------------------------------
update public.pipeline_steps set
  description_en = 'Find a winning product by analysing trends, demand, and competition.',
  prompt_template = 'أنت خبير في بحث المنتجات الرابحة للدروبشيبنغ باللغة العربية.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب:
1. تحليل حجم الطلب والاتجاهات (Google Trends, TikTok, Facebook)
2. تقييم المنافسة وتشبع السوق
3. تحليل هامش الربح المتوقع (سعر البيع - تكلفة المنتج - الشحن - الإعلانات)
4. أفضل 3 موردين مقترحين (AliExpress, CJ Dropshipping, Alibaba)
5. نقاط القوة والضعف
6. التوصية النهائية: ابدأ / لا تبدأ، مع السبب

احرص على أن تكون إجاباتك دقيقة وقابلة للتنفيذ، مع أرقام وبيانات حقيقية.'
where step_key = 'product_research';

update public.pipeline_steps set
  description_en = 'Analyse competitors, their ads, pricing, and offers.',
  prompt_template = 'أنت محلل منافسين متخصص في التجارة الإلكترونية.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب:
1. ابحث عن أكبر 5 منافسين يبيعون هذا المنتج أو مشابهاً له
2. لكل منافس: المتجر، السعر، العرض، نقاط التميز
3. تحليل إعلاناتهم (ما الذي يعمل معهم؟)
4. الثغرات والفرص التي يمكنك استغلالها
5. ما الذي يجعل عرضك مختلفاً؟

أخرج النتائج في جدول منظم قابل للنسخ إلى Excel.'
where step_key = 'competitor_research';

update public.pipeline_steps set
  description_en = 'Validate product viability and make a Go / No-Go decision.',
  prompt_template = 'بناءً على بحث المنتجات وبحث المنافسين التاليين، قيّم جدوى المنتج.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب:
1. ملخص نقاط القوة والضعف والفرص والمخاطر (SWOT)
2. مقارنة بين هامش الربح المتوقع والسوق المستهدف
3. تقييم جاهزية السوق (1-10)
4. القرار النهائي:
   - Go ✅: يمكن المتابعة للمرحلة التالية
   - Conditional Go ⚠️: يمكن المتابعة مع ملاحظات محددة
   - No Go ❌: المنتج غير مناسب، مع ذكر السبب

اكتب القرار في أول سطر بوضوح: GO أو CONDITIONAL_GO أو NO_GO'
where step_key = 'validation';

update public.pipeline_steps set
  description_en = 'Collect customer phrases, pain points, and marketing language.',
  prompt_template = 'أنت متخصص في علم نفس المستهلك وصياغة رسائل تسويقية باللغة العربية.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب:
1. 10 مشاكل وآلام يعانيها العميل المستهدف
2. 10 رغبات وأحلام يريد تحقيقها
3. 20 عبارة يستخدمها العميل عند وصف مشكلته (بلغة عامية واقعية)
4. الكلمات الأكثر تأثيراً في هذا السوق
5. الاعتراضات الشائعة وكيف تردّ عليها

الهدف: بناء مخزن لغوي نستخدمه في كتابة الإعلانات والعروض.'
where step_key = 'language_bank';

update public.pipeline_steps set
  description_en = 'Build an irresistible product offer.',
  prompt_template = 'أنت خبير في تصميم العروض التسويقية (Offer Design) للدروبشيبنغ.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب:
1. العنصر الأساسي للعرض (Core Offer): ما الذي يشتريه العميل فعلاً؟
2. المحسّنات (Bonuses): 3 إضافات مجانية أو محسوسة ترفع قيمة العرض
3. الضمان: اقترح ضماناً يزيل مخاوف الشراء
4. العرض الزمني (Urgency/Scarcity): كيف تخلق إلحاحية حقيقية؟
5. السعر المقترح وكيفية تقديمه (anchoring)
6. العنوان الرئيسي للعرض (Headline) — جملة واحدة لا تُقاوم

اكتب العرض الكامل جاهزاً للاستخدام في صفحة المنتج.'
where step_key = 'offer_creation';

update public.pipeline_steps set
  description_en = 'Calculate costs, margins, and unit profitability.',
  prompt_template = 'أنت محاسب متخصص في اقتصاديات وحدة الدروبشيبنغ.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — أعطني جدول اقتصاديات الوحدة كاملاً:
- تكلفة المنتج (من المورد)
- تكلفة الشحن إلى العميل
- رسوم المنصة (Shopify, PayPal)
- تكلفة الاستحواذ على العميل (CAC المستهدف)
- سعر البيع المقترح
- هامش الربح الصافي (بالقيمة والنسبة)
- نقطة التعادل (Break-even AOV)
- الحد الأقصى المسموح لتكلفة الإعلان (Max CPA)

قدّم 3 سيناريوهات: متفائل / واقعي / متحفظ.'
where step_key = 'unit_economics';

update public.pipeline_steps set
  description_en = 'Develop the advertising content strategy and creative angles.',
  prompt_template = 'أنت مدير إبداعي (Creative Director) متخصص في إعلانات الدروبشيبنغ.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — خطة الاستراتيجية الإبداعية:
1. 5 زوايا إعلانية مختلفة (Problem-Solution, Social Proof, Before/After, Demo, Story)
2. لكل زاوية: الفكرة الرئيسية + الرسالة الأساسية
3. الهوك المقترح لكل زاوية (Hook — أول 3 ثوانٍ)
4. نوع المحتوى المناسب: فيديو / صورة / كروسيل
5. الفئات المستهدفة المقترحة على Meta
6. أولوية الاختبار (أيها تبدأ به أولاً؟)'
where step_key = 'creative_strategy';

update public.pipeline_steps set
  description_en = 'Design the brand identity (colours, logo, tone).',
  prompt_template = 'أنت مصمم هوية بصرية متخصص في متاجر الدروبشيبنغ.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — كيت الهوية البصرية الكامل:
1. اسم العلامة التجارية المقترح (3 خيارات)
2. لون رئيسي + ثانوي + محايد (مع كودات Hex)
3. نبرة الصوت (Tone of Voice): رسمي/غير رسمي، دافئ/حازم...
4. أسلوب الصور المقترح
5. الكلمات الدالة على الهوية (Brand Keywords)
6. مثال على كيف تصف العلامة نفسها في جملة واحدة (Brand Statement)

تأكد أن الهوية تناسب السوق العربي وقيم العملاء المستهدفين.'
where step_key = 'branding_kit';

update public.pipeline_steps set
  description_en = 'Write ad copy and video scripts.',
  prompt_template = 'أنت كاتب محتوى إعلاني (Copywriter) متخصص في Meta Ads باللغة العربية.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — اكتب لكل زاوية من الزوايا الإبداعية:
1. سكربت فيديو (15-30 ثانية): هوك + جسم + CTA
2. نص إعلان (Ad Copy): عنوان + وصف + CTA
3. هوكات بديلة (3 هوكات لكل سكربت)

تأكد من:
- استخدام اللغة التي جمعناها في بنك اللغة
- مطابقة نبرة الهوية البصرية
- وضوح الـ CTA وتناسبه مع المرحلة (Awareness/Consideration/Conversion)'
where step_key = 'ad_scripts';

update public.pipeline_steps set
  description_en = 'Produce static images and advertising videos (using Higgsfield).',
  required_mcps = '{Higgsfield}'
where step_key = 'creative_production';

update public.pipeline_steps set
  description_en = 'Build the product page on Shopify.',
  prompt_template = 'أنت متخصص في تحسين صفحات المنتجات (PDP) على Shopify للسوق العربي.

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — صفحة منتج كاملة:
1. العنوان الرئيسي (مع كلمة مفتاحية SEO)
2. الوصف الطويل (800-1200 كلمة): القصة + الفوائد + المواصفات + الضمان
3. نقاط البيع الرئيسية (Bullet Points) — 5 نقاط
4. قسم الأسئلة الشائعة (FAQ) — 6 أسئلة
5. نص زر الشراء + الرسالة تحته (Trust badge)
6. Title tag + Meta description للـ SEO

اكتب كل شيء باللغة العربية جاهزاً للنسخ والتطبيق على Shopify.'
where step_key = 'pdp';

update public.pipeline_steps set
  description_en = 'Build the Meta advertising campaign.',
  prompt_template = 'أنت خبير في بناء حملات Meta Ads (Facebook/Instagram).

المنتج: {{product_name}}
السوق المستهدف: {{target_market}}

المطلوب — خطة بناء الحملة:
1. هيكل الحملة: Campaigns → Ad Sets → Ads
2. الهدف المقترح (Conversions, Traffic, Reach)
3. الميزانية اليومية المقترحة للاختبار
4. الجماهير المستهدفة (Interests, Lookalike, Retargeting)
5. جدول اختبار الكرييتف (أيها نختبر أولاً؟)
6. مقاييس النجاح (KPIs): ROAS المستهدف، CPA الأقصى، CTR المتوقع
7. متى تتوقف، متى تُضاعف (Scaling Rules)'
where step_key = 'meta_campaign';

update public.pipeline_steps set
  description_en = 'Analyse campaign performance (CPA, ROAS) — repeatable.'
where step_key = 'campaign_analysis';

update public.pipeline_steps set
  description_en = 'Optimise the store for search engines.'
where step_key = 'seo';

update public.pipeline_steps set
  description_en = 'Prepare the monthly Profit & Loss statement — repeatable.'
where step_key = 'pl_workbook';

-- ---------------------------------------------------------------------------
-- advance_pipeline: approve a step and unlock the next one(s).
-- Called by the server-side upload route with the service-role client,
-- so it runs in a SECURITY DEFINER context to write progress rows that
-- students cannot write directly.
--
-- Unlock map (step_id == sort_order in this schema):
--   1 → 2 → 3 → 4 → 5 → 6 → 7 → 8
--   8 → 9, 11, 14   (three parallel unlocks)
--   9 → 10
--   10 + 11 → 12    (AND gate)
--   12 → 13, 15
-- ---------------------------------------------------------------------------
create or replace function public.advance_pipeline(
  p_brand_id uuid,
  p_step_id  int
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_repeatable  boolean;
  v_current_status text;
  v_other_approved boolean;
  v_unlock_ids     int[] := '{}';
begin
  -- Verify the caller can see this brand (owner or admin).
  if not exists (
    select 1 from public.brands
    where id = p_brand_id
      and (owner_id = auth.uid() or public.is_ecomskool_admin())
  ) then
    return jsonb_build_object('ok', false, 'error', 'brand_not_found');
  end if;

  -- Fetch step metadata.
  select is_repeatable into v_is_repeatable
  from public.pipeline_steps where id = p_step_id;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'step_not_found');
  end if;

  -- Fetch current progress status.
  select status into v_current_status
  from public.brand_step_progress
  where brand_id = p_brand_id and step_id = p_step_id;

  -- Reject locked steps.
  if v_current_status = 'locked' then
    return jsonb_build_object('ok', false, 'error', 'step_locked');
  end if;

  -- For already-approved non-repeatable steps: the file was already stored
  -- (caller creates step_files row first), but we skip re-gating.
  if v_current_status = 'approved' and not v_is_repeatable then
    return jsonb_build_object('ok', true, 'already_approved', true);
  end if;

  -- Approve this step.
  update public.brand_step_progress
  set status = 'approved', completed_at = now()
  where brand_id = p_brand_id and step_id = p_step_id;

  -- Determine which steps to unlock (using step_id which equals sort_order).
  case p_step_id
    when 1  then v_unlock_ids := array[2];
    when 2  then v_unlock_ids := array[3];
    when 3  then v_unlock_ids := array[4];
    when 4  then v_unlock_ids := array[5];
    when 5  then v_unlock_ids := array[6];
    when 6  then v_unlock_ids := array[7];
    when 7  then v_unlock_ids := array[8];
    when 8  then v_unlock_ids := array[9, 11, 14];  -- parallel launch
    when 9  then v_unlock_ids := array[10];
    when 10 then
      -- AND gate: unlock step 12 only if step 11 is also approved.
      select (status = 'approved') into v_other_approved
      from public.brand_step_progress where brand_id = p_brand_id and step_id = 11;
      if coalesce(v_other_approved, false) then
        v_unlock_ids := array[12];
      end if;
    when 11 then
      -- AND gate: unlock step 12 only if step 10 is also approved.
      select (status = 'approved') into v_other_approved
      from public.brand_step_progress where brand_id = p_brand_id and step_id = 10;
      if coalesce(v_other_approved, false) then
        v_unlock_ids := array[12];
      end if;
    when 12 then v_unlock_ids := array[13, 15];
    else v_unlock_ids := '{}';
  end case;

  -- Unlock the next steps (only those currently locked).
  if array_length(v_unlock_ids, 1) > 0 then
    update public.brand_step_progress
    set status = 'unlocked', unlocked_at = now()
    where brand_id = p_brand_id
      and step_id = any(v_unlock_ids)
      and status = 'locked';
  end if;

  return jsonb_build_object('ok', true, 'unlocked', v_unlock_ids);
end;
$$;
